title: KeepAccounts
email: swalloworks@gmail.com
author: Swalloworks Studio
description: >- # this means to ignore newlines until "baseurl:"
  家計簿 小遣い帳 かんたん 収支 レシート 支出 簡単 シンプル 便利 フリー マネー
  お金 管理 節約 kakeibo プロー free money expense spend 记账 账本.
url: "http://kakeibo.swalloworkstudio.com"

# Build settings
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-multiple-languages-plugin

langs:
  en: English
  ja: 日本語
  zh_CN: 简体中文
  zh_TW: 繁體中文
# jekyll-multiple-languages-plugin settings:
languages: ["en", "ja", "zh_CN", "zh_TW"]
exclude_from_localizations:
  - js
  - fonts
  - img
  - css
  - favicon.ico

social:
  - title: twitter
    url: http://twitter.com/swalloworks
  - title: linkedin
    url: http://jp.linkedin.com/pub/xuan-renliang/40/68/ba4

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
